name = "scrum-slinger"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production.vars]
VITE_API_BASE_URL = "https://scrum-poker-ibr29q.fly.dev"
VITE_WS_BASE_URL = "wss://scrum-poker-ibr29q.fly.dev"

[env.preview.vars]
VITE_API_BASE_URL = "https://scrum-poker-ibr29q.fly.dev"
VITE_WS_BASE_URL = "wss://scrum-poker-ibr29q.fly.dev"